[2025-09-18T05:36:34.703+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-18T05:36:34.736+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_b scheduled__2025-09-17T00:00:00+00:00 [queued]>
[2025-09-18T05:36:34.752+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_b scheduled__2025-09-17T00:00:00+00:00 [queued]>
[2025-09-18T05:36:34.753+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-18T05:36:34.779+0000] {taskinstance.py:2888} INFO - Executing <Task(ExternalPythonOperator): ext_py_b> on 2025-09-17 00:00:00+00:00
[2025-09-18T05:36:34.793+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=354) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-18T05:36:34.801+0000] {standard_task_runner.py:72} INFO - Started process 364 to run task
[2025-09-18T05:36:34.800+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_branch_operator', 'ext_py_b', 'scheduled__2025-09-17T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator.py', '--cfg-path', '/tmp/tmprw3olocx']
[2025-09-18T05:36:34.803+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask ext_py_b
[2025-09-18T05:36:34.963+0000] {task_command.py:467} INFO - Running <TaskInstance: example_branch_operator.ext_py_b scheduled__2025-09-17T00:00:00+00:00 [running]> on host 7f8c5cf1dc7b
[2025-09-18T05:36:35.155+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_operator' AIRFLOW_CTX_TASK_ID='ext_py_b' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-17T00:00:00+00:00'
[2025-09-18T05:36:35.163+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-18T05:36:35.164+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-18T05:36:35.166+0000] {logging_mixin.py:190} INFO - Current task name:ext_py_b state:running start_date:2025-09-18 05:36:34.737674+00:00
[2025-09-18T05:36:35.167+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_operator and current dag run status:running
[2025-09-18T05:36:35.168+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-18T05:36:35.724+0000] {baseoperator.py:405} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2025-09-18T05:36:35.798+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-callmv1yqdn6/script.py /tmp/venv-callmv1yqdn6/script.in /tmp/venv-callmv1yqdn6/script.out /tmp/venv-callmv1yqdn6/string_args.txt /tmp/venv-callmv1yqdn6/termination.log
[2025-09-18T05:36:35.800+0000] {process_utils.py:190} INFO - Output:
[2025-09-18T05:36:42.843+0000] {process_utils.py:194} INFO - Hello World from external Python
[2025-09-18T05:36:43.465+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-09-18T05:36:43.481+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-18T05:36:43.481+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=example_branch_operator, task_id=ext_py_b, run_id=scheduled__2025-09-17T00:00:00+00:00, execution_date=20250917T000000, start_date=20250918T053634, end_date=20250918T053643
[2025-09-18T05:36:43.495+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-09-18T05:36:43.496+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-09-18T05:36:43.496+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_operator queued_at:2025-09-18 05:36:16.817458+00:00
[2025-09-18T05:36:43.497+0000] {logging_mixin.py:190} INFO - Task hostname:7f8c5cf1dc7b operator:ExternalPythonOperator
[2025-09-18T05:36:43.527+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-18T05:36:43.578+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T05:36:43.581+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
